
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage , Frame


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Project\Hospital main final\gui\mainwindow\titles\about")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def about_title():
    About_title

class About_title(Frame):
    def __init__(self,parent,*args,**kwargs):
        Frame.__init__(self,parent,*args,**kwargs)
        self.parent = parent

        self.configure(bg = "#F9E6EE")


        canvas = Canvas(
            self,
            bg = "#F9E6EE",
            height = 62,
            width = 798,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        self.image1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            63.0,
            31.0,
            image=self.image1
        )

        self.image2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = canvas.create_image(
            771.0,
            31.0,
            image=self.image2
        )

        self.image3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = canvas.create_image(
            379.0,
            53.99999999999983,
            image=self.image3
        )

        self.image4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = canvas.create_image(
            399.0,
            31.0,
            image=self.image4
        )

        canvas.create_text(
            686.0,
            22.0,
            anchor="nw",
            text="Admin",
            fill="#716F6F",
            font=("Montserrat Bold", 15 * -1)
        )