
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,Frame


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Project\Hospital main final\gui\mainwindow\titles\appointment")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def appointment_title():
    Appointment_title

class Appointment_title(Frame):
    def __init__(self,parent,*args,**kwargs):
        Frame.__init__(self,parent,*args,**kwargs)
        self.parent = parent
        self.configure(bg = "#F9E6EE")


        canvas = Canvas(
            self,
            bg = "#F9E6EE",
            height = 62,
            width = 798,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        self.image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            399.0,
            30.0,
            image=self.image_1
        )

        canvas.create_text(
            686.0,
            22.0,
            anchor="nw",
            text="Admin",
            fill="#716F6F",
            font=("Montserrat Bold", 15 * -1)
        )

        self.image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = canvas.create_image(
            93.0,
            31.0,
            image=self.image_2
        )

        self.image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = canvas.create_image(
            770.0,
            31.0,
            image=self.image_3
        )

        self.image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = canvas.create_image(
            370.99592944746837,
            57.0,
            image=self.image_4
        )
