
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Frame, Canvas, Entry, Text, Button, PhotoImage, messagebox

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Project\Hospital main final\gui\mainwindow\about\assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def about():
    About()

class About(Frame):
    def __init__(self, parent, *args, **kwargs):
        Frame.__init__(self, parent, *args, **kwargs)
        self.parent = parent


        self.configure(bg = "#F9E5EE")


        self.canvas = Canvas(
            self,
            bg = "#F9E5EE",
            height = 432,
            width = 797,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
        image_1 = self.canvas.create_image(
            507.0,
            208.0,
            image=self.image_image_1
        )

        self.image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
        image_2 = self.canvas.create_image(
            169.0,
            239.0,
            image=self.image_image_2
        )

        self.image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
        image_3 = self.canvas.create_image(
            190.9999997377222,
            73.99989175796509,
            image=self.image_image_3
        )

        self.image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = self.canvas.create_image(
            141.0,
            215.0,
            image=self.image_image_4
        )

        self.image_image_5 = PhotoImage(
            file=relative_to_assets("image_5.png"))
        image_5 = self.canvas.create_image(
            140.0,
            216.0,
            image=self.image_image_5
        )

        self.image_image_6 = PhotoImage(
            file=relative_to_assets("image_6.png"))
        image_6 = self.canvas.create_image(
            396.0,
            217.0,
            image=self.image_image_6
        )

        self.image_image_7 = PhotoImage(
            file=relative_to_assets("image_7.png"))
        image_7 = self.canvas.create_image(
            651.0,
            217.0,
            image=self.image_image_7
        )

        self.canvas.create_text(
            56.0,
            121.0,
            anchor="nw",
            text="Master",
            fill="#777777",
            font=("Montserrat SemiBold", 15 * -1)
        )

        self.canvas.create_text(
            53.0,
            135.0,
            anchor="nw",
            text="Uttkarsh",
            fill="#FABBA9",
            font=("Montserrat Bold", 26 * -1)
        )

        self.image_image_8 = PhotoImage(
            file=relative_to_assets("image_8.png"))
        image_8 = self.canvas.create_image(
            200.0,
            140.0,
            image=self.image_image_8
        )

        self.image_image_9 = PhotoImage(
            file=relative_to_assets("image_9.png"))
        image_9 = self.canvas.create_image(
            112.99999982515362,
            170.99999022483826,
            image=self.image_image_9
        )

        self.canvas.create_text(
            179.0,
            47.0,
            anchor="nw",
            text="Featuring.....",
            fill="#317285",
            font=("ShantellSans Medium", 18 * -1)
        )

        self.image_image_10 = PhotoImage(
            file=relative_to_assets("image_10.png"))
        image_10 = self.canvas.create_image(
            140.0,
            37.0,
            image=self.image_image_10
        )

        self.image_image_11 = PhotoImage(
            file=relative_to_assets("image_11.png"))
        image_11 = self.canvas.create_image(
            652.0,
            218.0,
            image=self.image_image_11
        )

        self.canvas.create_text(
            571.0,
            135.0,
            anchor="nw",
            text="Divyank",
            fill="#FABBA9",
            font=("Montserrat Bold", 26 * -1)
        )

        self.image_image_12 = PhotoImage(
            file=relative_to_assets("image_12.png"))
        image_12 = self.canvas.create_image(
            395.0,
            218.0,
            image=self.image_image_12
        )

        self.image_image_13 = PhotoImage(
            file=relative_to_assets("image_13.png"))
        image_13 = self.canvas.create_image(
            449.0,
            135.0,
            image=self.image_image_13
        )

        self.image_image_14 = PhotoImage(
            file=relative_to_assets("image_14.png"))
        image_14 = self.canvas.create_image(
            364.9999998251536,
            170.99999022483826,
            image=self.image_image_14
        )

        self.image_image_15 = PhotoImage(
            file=relative_to_assets("image_15.png"))
        image_15 = self.canvas.create_image(
            624.9999998251536,
            170.99999022483826,
            image=self.image_image_15
        )

        self.canvas.create_text(
            57.0,
            175.0,
            anchor="nw",
            text='"Hi, I’m Uttkarsh – a tech\n enthusiast with a knack for\n gadgets and a love for\n innovation. When I’m not\n geeking out over the latest\n tech, you’ll probably find me\n catching up on sleep or\n enjoying lively conversations\n while wandering through life’s\n social adventures."',
            fill="#317285",
            font=("Montserrat Bold", 10 * -1)
        )

        self.canvas.create_text(
            309.0,
            175.0,
            anchor="nw",
            text='“Hi, I’m Shruti - With a creative\n and innovative mindset, I am\n passionate about exploring the\n endless possibilities that color\n offers in design. I thrive on\n pushing boundaries and\n integrating the latest technology\n and impactful visual experiences.\n evolving and staying ahead of\n trends”',
            fill="#317285",
            font=("Montserrat Bold", 10 * -1)
        )

        self.canvas.create_text(
            571.0,
            121.0,
            anchor="nw",
            text="AeroCircuit",
            fill="#777777",
            font=("Montserrat Bold", 15 * -1)
        )

        self.canvas.create_text(
            314.0,
            121.0,
            anchor="nw",
            text="PixelBloom",
            fill="#777777",
            font=("Montserrat Bold", 15 * -1)
        )

        self.canvas.create_text(
            314.0,
            135.0,
            anchor="nw",
            text="Shruti",
            fill="#FABBA9",
            font=("Montserrat Bold", 26 * -1)
        )

        self.canvas.create_text(
            569.0,
            175.0,
            anchor="nw",
            text='''"Hi, I’m Divyank – a laid-back\n soul who finds joy in the simple\n things. I’m passionate about\n coding, captivated by nature’s\n beauty, and always up for a\n good gaming session. Life’s\n about balance, and I love\n spending my time creating,\n exploring, and enjoying the\n little moments."''',
            fill="#317285",
            font=("Montserrat Bold", 10 * -1)
        )

        self.image_image_16 = PhotoImage(
            file=relative_to_assets("image_16.png"))
        image_16 = self.canvas.create_image(
            711.0,
            136.0,
            image=self.image_image_16
        )